Repository cevap/ion, pull requests merged in 2018-12, with the labels that each got.

#81 Add in config.guess and config.sub from depends
  snap/snapcraft.yaml
Labels: Build system, Scripts and tools

#88 Change BIP44 for ION
  src/chainparams.cpp
Labels: Needs release notes

#93 #91 Update accumulator checkpoints
  src/accumulatorcheckpoints.json.h
Labels: UTXO Db and Indexes

#99 Set supermajority fork parameters to switch to block version 9, not b…
  src/main.cpp
Labels: Bug

#127 Set locks on cs_wallet for SelectCoinsMasternode() which is called by…
  src/activemasternode.cpp
Labels: Bug
